<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Tutorial_Moran.knit</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="projectlab.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="in_GEOG364_FAQ.html">FAQs</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    YOUR LABS
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="in_GEOG364_Lab1.html">Lab 1: Basics</a>
    </li>
    <li>
      <a href="in_GEOG364_Lab2.html">Lab 2: Data summary</a>
    </li>
    <li>
      <a href="in_GEOG364_Lab4.html">Lab 4: Spatial Wrangling</a>
    </li>
    <li>
      <a href="in_GEOG364_Lab5.html">Lab 5: Moran's I</a>
    </li>
    <li>
      <a href="in_GEOG364_Lab6.html">Lab 6: LISA and regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Advanced Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Tutorial_CensusData.html">Getting Census Data</a>
    </li>
    <li>
      <a href="Tutorial_SpatWeights.html">Spatial Weights Matrices</a>
    </li>
    <li>
      <a href="Tutorial_Moran.html">Moran's I</a>
    </li>
    <li>
      <a href="Tutorial_LISA.html">LISA</a>
    </li>
    <li>
      <a href="Tutorial_Regression.html">Regression</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    TURTLES
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Turtle_tutorial.html">Tutorial</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<p><br></p>
<div id="tutorial-autocorrelation-spatial-weights"
class="section level1">
<h1>TUTORIAL Autocorrelation &amp; Spatial Weights</h1>
<div id="check-before-you-start" class="section level2">
<h2>Check before you start</h2>
<p>Here is how I load the example data for this tutorial which focuses
on 2020 median per capita income for the state of Maine.</p>
<details>
<summary>
<strong>Code to load the example data. IF YOU’RE DOING LAB 5 this was
covered in week 1</strong>
</summary>
<p><br></p>
<p>First make sure all of these libraries are at the top of your lab
script in a code chunk, and run the code chunk! If you run the code
chunk and it says a package is missing, either click “install” if the
little yellow bar appears at the top, or go to the Packages tab, and
click Install to go to the package ‘app store’.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a><span class="fu">library</span>(sfdep)</span>
<span id="cb1-14"><a href="#cb1-14" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb1-15"><a href="#cb1-15" tabindex="-1"></a><span class="fu">library</span>(units)</span>
<span id="cb1-16"><a href="#cb1-16" tabindex="-1"></a><span class="fu">library</span>(sfdep)</span>
<span id="cb1-17"><a href="#cb1-17" tabindex="-1"></a><span class="fu">library</span>(spatstat)</span></code></pre></div>
<p><br></p>
<p>Then you can load your data from the census and tidy up, before
plotting</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># Download some data for Maine and NH using get_acs</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="co"># THIS WILL NOT WORK IF YOU DID&#39;T RUN YOUR API KEY CODE &amp; RESTART R-STUDIO</span></span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>ACS_county.sf <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">&quot;county&quot;</span>, </span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>                         <span class="at">year =</span> <span class="dv">2019</span>,</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>                         <span class="at">variables =</span> <span class="fu">c</span>(<span class="at">housevalue  =</span> <span class="st">&quot;B25075_001&quot;</span>,  <span class="co"># house value</span></span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a>                                       <span class="at">total_pop   =</span> <span class="st">&quot;B05012_001&quot;</span>,  <span class="co"># total population</span></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a>                                       <span class="at">total_house =</span> <span class="st">&quot;B25001_001&quot;</span>,  <span class="co"># no. houses</span></span>
<span id="cb2-8"><a href="#cb2-8" tabindex="-1"></a>                                       <span class="at">med.income  =</span> <span class="st">&quot;B19013_001&quot;</span>), <span class="co"># median income  </span></span>
<span id="cb2-9"><a href="#cb2-9" tabindex="-1"></a>                         <span class="at">state =</span> <span class="fu">c</span>(<span class="st">&quot;ME&quot;</span>),</span>
<span id="cb2-10"><a href="#cb2-10" tabindex="-1"></a>                         <span class="at">survey =</span> <span class="st">&quot;acs5&quot;</span>, <span class="at">geometry =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-11"><a href="#cb2-11" tabindex="-1"></a>                         <span class="at">output =</span> <span class="st">&quot;wide&quot;</span>, <span class="at">show_call =</span> <span class="cn">FALSE</span>)</span>
<span id="cb2-12"><a href="#cb2-12" tabindex="-1"></a><span class="co">#st_coordinates(ACS_county.sf)</span></span>
<span id="cb2-13"><a href="#cb2-13" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" tabindex="-1"></a><span class="co"># OPTIONAL. For more advanced work, you probably want to keep the error columns</span></span>
<span id="cb2-15"><a href="#cb2-15" tabindex="-1"></a><span class="co"># If you don&#39;t run it, remember all your columns have an E on the end of the name </span></span>
<span id="cb2-16"><a href="#cb2-16" tabindex="-1"></a>ACS_county.sf <span class="ot">&lt;-</span> ACS_county.sf <span class="sc">%&gt;%</span></span>
<span id="cb2-17"><a href="#cb2-17" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb2-18"><a href="#cb2-18" tabindex="-1"></a>    GEOID, </span>
<span id="cb2-19"><a href="#cb2-19" tabindex="-1"></a>    NAME,</span>
<span id="cb2-20"><a href="#cb2-20" tabindex="-1"></a>    <span class="at">housevalue   =</span> housevalueE, </span>
<span id="cb2-21"><a href="#cb2-21" tabindex="-1"></a>    <span class="at">total_pop    =</span> total_popE, </span>
<span id="cb2-22"><a href="#cb2-22" tabindex="-1"></a>    <span class="at">total_house  =</span> total_houseE, </span>
<span id="cb2-23"><a href="#cb2-23" tabindex="-1"></a>    <span class="at">med.income   =</span> med.incomeE,</span>
<span id="cb2-24"><a href="#cb2-24" tabindex="-1"></a>    geometry </span>
<span id="cb2-25"><a href="#cb2-25" tabindex="-1"></a>    )</span>
<span id="cb2-26"><a href="#cb2-26" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" tabindex="-1"></a><span class="co">#st_coordinates(ACS_county.sf)</span></span>
<span id="cb2-28"><a href="#cb2-28" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" tabindex="-1"></a><span class="co"># Change the map projection to Albers equal projection, </span></span>
<span id="cb2-31"><a href="#cb2-31" tabindex="-1"></a><span class="co"># then remove empty polygons (lakes etc) and fix any broken geometry</span></span>
<span id="cb2-32"><a href="#cb2-32" tabindex="-1"></a>ACS_county.sf <span class="ot">&lt;-</span> ACS_county.sf <span class="sc">%&gt;%</span></span>
<span id="cb2-33"><a href="#cb2-33" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">5070</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-34"><a href="#cb2-34" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">st_is_empty</span>(geometry)) <span class="sc">%&gt;%</span></span>
<span id="cb2-35"><a href="#cb2-35" tabindex="-1"></a>  <span class="fu">st_make_valid</span>()</span>
<span id="cb2-36"><a href="#cb2-36" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" tabindex="-1"></a><span class="co"># Find the areas in each county &amp; change the units from metres squared to km squared</span></span>
<span id="cb2-39"><a href="#cb2-39" tabindex="-1"></a>ACS_county.sf<span class="sc">$</span>Area  <span class="ot">&lt;-</span> <span class="fu">st_area</span>(ACS_county.sf)</span>
<span id="cb2-40"><a href="#cb2-40" tabindex="-1"></a>ACS_county.sf<span class="sc">$</span>Area  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">set_units</span>(ACS_county.sf<span class="sc">$</span>Area,<span class="st">&quot;km^2&quot;</span>))</span>
<span id="cb2-41"><a href="#cb2-41" tabindex="-1"></a></span>
<span id="cb2-42"><a href="#cb2-42" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" tabindex="-1"></a><span class="co"># OPTIONAL &amp; DEPENDS ON THE VARIABLES YOU DOWNLOAD</span></span>
<span id="cb2-45"><a href="#cb2-45" tabindex="-1"></a><span class="co"># Divide the total population &amp; housing by the area to give the population/housing density</span></span>
<span id="cb2-46"><a href="#cb2-46" tabindex="-1"></a>ACS_county.sf<span class="sc">$</span>pop_density_km2  <span class="ot">&lt;-</span> ACS_county.sf<span class="sc">$</span>total_pop   <span class="sc">/</span> ACS_county.sf<span class="sc">$</span>Area</span>
<span id="cb2-47"><a href="#cb2-47" tabindex="-1"></a>ACS_county.sf<span class="sc">$</span>house_density_km2 <span class="ot">&lt;-</span> ACS_county.sf<span class="sc">$</span>total_house <span class="sc">/</span> ACS_county.sf<span class="sc">$</span>Area</span>
<span id="cb2-48"><a href="#cb2-48" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" tabindex="-1"></a><span class="co">#SPATIAL WEIGHTS - I chose 1st order QUEENS</span></span>
<span id="cb2-51"><a href="#cb2-51" tabindex="-1"></a><span class="co"># First get the geometry/coords </span></span>
<span id="cb2-52"><a href="#cb2-52" tabindex="-1"></a><span class="co"># Then the central point in each polygon</span></span>
<span id="cb2-53"><a href="#cb2-53" tabindex="-1"></a><span class="co"># Finally, extract the Queens neigbours</span></span>
<span id="cb2-54"><a href="#cb2-54" tabindex="-1"></a><span class="co"># and get the spatial weights matrix</span></span>
<span id="cb2-55"><a href="#cb2-55" tabindex="-1"></a>ACS_county.geometry <span class="ot">&lt;-</span> <span class="fu">st_geometry</span>(ACS_county.sf)</span>
<span id="cb2-56"><a href="#cb2-56" tabindex="-1"></a>ACS_county.centroid <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(ACS_county.sf)</span>
<span id="cb2-57"><a href="#cb2-57" tabindex="-1"></a>neighbor.queens   <span class="ot">&lt;-</span> <span class="fu">st_contiguity</span>(ACS_county.geometry, <span class="at">queen=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-58"><a href="#cb2-58" tabindex="-1"></a>weights.queens <span class="ot">&lt;-</span> <span class="fu">st_weights</span>(neighbor.queens)</span></code></pre></div>
</details>
<div class="small-gap">

</div>
<p><br></p>
</div>
<div id="morans-i-scatterplot" class="section level2">
<h2>Moran’s I scatterplot</h2>
<p>Once we’ve defined a neighborhood for our analysis, we identify the
neighbors for each polygon in our dataset then summaries the values for
each neighborhood cluster (by computing their mean values, for example).
This summarized neighborhood value is sometimes referred to as a
spatially lagged value (<em>X<sub>lag</sub></em>).</p>
<p>Using R, it’s now very easy for us to calculate the Moran’s I
scatterplot</p>
<p>The old spdep package has a very easy scatterplot function to make a
moran’s plot. But unfortunately the new sfdep package has not yet
followed suit. so here’s a work-around</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># PUT THIS IN YOUR LIRBARY CODE CHUNK &amp; RUN/INSTALL</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">library</span>(spdep)</span></code></pre></div>
<pre><code>## Loading required package: spData</code></pre>
<pre><code>## To access larger datasets in this package, install the spDataLarge
## package with: `install.packages(&#39;spDataLarge&#39;,
## repos=&#39;https://nowosad.github.io/drat/&#39;, type=&#39;source&#39;)`</code></pre>
<pre><code>## 
## Attaching package: &#39;spData&#39;</code></pre>
<pre><code>## The following object is masked _by_ &#39;.GlobalEnv&#39;:
## 
##     house</code></pre>
<pre><code>## The following object is masked from &#39;package:openintro&#39;:
## 
##     house</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># calculate the sp version of weights </span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>weights.queens.sp <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">nb2listw</span>(neighbor.queens)</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a>  </span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a><span class="co"># and plot , the first line adjusts the margins to make it neater.</span></span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">1</span>,<span class="dv">1</span>))   </span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a><span class="fu">moran.plot</span>(ACS_county.sf<span class="sc">$</span>housevalue, </span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a>           weights.queens.sp, </span>
<span id="cb9-8"><a href="#cb9-8" tabindex="-1"></a>           <span class="at">xlab  =</span> <span class="st">&quot;Average House Value per county (USD)&quot;</span>,</span>
<span id="cb9-9"><a href="#cb9-9" tabindex="-1"></a>           <span class="at">ylab  =</span> <span class="st">&quot;Average house value of </span><span class="sc">\n</span><span class="st"> neighbouring counties (Queens 1st)&quot;</span>,</span>
<span id="cb9-10"><a href="#cb9-10" tabindex="-1"></a>           <span class="at">labels=</span>ACS_county.sf<span class="sc">$</span>NAME,</span>
<span id="cb9-11"><a href="#cb9-11" tabindex="-1"></a>            <span class="at">zero.policy =</span> T)</span></code></pre></div>
<p><img src="Tutorial_Moran_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><br></p>
<p>We then plot <em>HouseValue<sub>lag</sub></em> against
<em>HouseValue</em> for each county. A positive slope means positive
autocorrelation (smooth clusters, high values surrounded by high
values). A negative slope means negative autocorrelation (high
surrounded by low, chessboard effect).</p>
<p><br><br></p>
</div>
<div id="calculating-morans-i" class="section level2">
<h2>Calculating Morans I</h2>
<p>The Moran’s <em>I</em> coefficient between
<em>HouseValue<sub>lag</sub></em> and <em>HouseValue</em> is nothing
more than the slope of the least squares regression line that best fits
the points <em>after</em> standardizing both variables (i.e., converting
them to z-scores), which centers them on the mean and scales them by
their standard deviation.</p>
<p>The global_moran function outputs the global Moran’s I along with the
average number of neighbours.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>MoranI_HouseValue <span class="ot">&lt;-</span> <span class="fu">global_moran</span>(ACS_county.sf<span class="sc">$</span>housevalue, </span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>                                  <span class="at">nb =</span> neighbor.queens,</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>                                  <span class="at">wt =</span> weights.queens)</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>MoranI_HouseValue</span></code></pre></div>
<pre><code>## $I
## [1] 0.1241145
## 
## $K
## [1] 4.586472</code></pre>
<p>In fact, lets add it as a title to the scatterplot.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># and plot , the first line adjusts the margins to make it neater.</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">1</span>))   </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">moran.plot</span>(ACS_county.sf<span class="sc">$</span>housevalue, </span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>           weights.queens.sp, </span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>           <span class="at">xlab  =</span> <span class="st">&quot;Average House Value per county (USD)&quot;</span>,</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>           <span class="at">ylab  =</span> <span class="st">&quot;Average house value of </span><span class="sc">\n</span><span class="st"> neighbouring counties (Queens 1st)&quot;</span>,</span>
<span id="cb12-7"><a href="#cb12-7" tabindex="-1"></a>           <span class="at">labels=</span>ACS_county.sf<span class="sc">$</span>NAME,</span>
<span id="cb12-8"><a href="#cb12-8" tabindex="-1"></a>           <span class="at">zero.policy =</span> T,</span>
<span id="cb12-9"><a href="#cb12-9" tabindex="-1"></a>           <span class="at">main=</span> <span class="fu">paste</span>(<span class="st">&quot;Global Moran&#39;s I:&quot;</span>,<span class="fu">round</span>(MoranI_HouseValue<span class="sc">$</span>I,<span class="dv">3</span>)))</span></code></pre></div>
<p><img src="Tutorial_Moran_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="morans-hypothesis-test" class="section level2">
<h2>Moran’s Hypothesis test</h2>
<p>If there is no degree of association between <em>HouseValue</em> and
<em>HouseValue<sub>lag</sub></em>, the slope will be close to flat
(resulting in a Moran’s <em>I</em> value near 0). In our working
example, the slope is far from flat. So this raises the question: how
significant is this Moran’s <em>I</em> value (i.e. is the computed slope
significantly different from 0)? There are two approaches to estimating
the significance: an analytical solution and a Monte Carlo solution.</p>
<p>The analytical solution makes some restrictive assumptions about the
data and thus cannot always be reliable. The other approach (and the one
favored here) is a Monte Carlo test. This approach avoids parametric
assumptions about the data distribution or spatial layout, relying
instead on the assumption that values are exchangeable under the null
hypothesis.</p>
<p>In a Monte Carlo test (specifically, a permutation-based bootstrap
test) we assess the significance of an observed Moran’s <em>I</em>
statistic by comparing it to a distribution of values generated under
the null hypothesis of spatial randomness. This is done by
<strong>permuting</strong> the attribute values across spatial units
while keeping the spatial structure (e.g., neighborhood relationships)
fixed.</p>
<p>Here’s the quick code to do this.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="fu">global_moran_perm</span>(ACS_county.sf<span class="sc">$</span>housevalue, </span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>                   <span class="at">nb =</span> neighbor.queens,</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>                   <span class="at">wt =</span> weights.queens,</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>                   <span class="at">alternative=</span><span class="st">&quot;two.sided&quot;</span>, <span class="co">#Should be one of &quot;greater&quot;, &quot;less&quot;, or &quot;two.sided&quot;</span></span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>                   <span class="at">nsim=</span> <span class="dv">1000</span>) </span></code></pre></div>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  x 
## weights: listw  
## number of simulations + 1: 1001 
## 
## statistic = 0.12411, observed rank = 913, p-value = 0.1758
## alternative hypothesis: two.sided</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="fl">0.2098</span></span></code></pre></div>
<pre><code>## [1] 4.766444</code></pre>
<p>So in this case,</p>
<ul>
<li>H0: The pattern in housevalues was caused by an indepedent random
process</li>
<li>H1: The Global Moran’s I value is so different to what we would
expect, we think H0 is false and that there is another process causing
housevalues to be clustered or gridded.</li>
</ul>
<p>Or mathematically</p>
<ul>
<li>H0: Global Moran’s I = 0</li>
<li>H1: Global Moran’s I != 0</li>
</ul>
<p>Then</p>
<ul>
<li>Observed statistic: Global Moran’s I: 0.12411</li>
<li>p-value = 0.2098.</li>
</ul>
<p>We’re likely to see patterns with Moran’s I &gt;= 0.124 almost 20% of
the time. AKA nearly 1 in 5 random patterns are likely to have a Moran’s
I value this extreme. (1/0.2098 = 4.766). This is a pretty high
likelyhood of seeing a pattern like this. Normally we only trust results
with p &lt; 0.05, where a H0 would only happen by chance 1 time in
20.</p>
<p>So in this case, I don’t think we have enough evidence to reject H0.
E.g. there’s no evidence the autocorrelation of housevalues is
significant (p=0.2098)</p>
<p>We are going to interpret this in detail during class, or see here <a
href="https://mgimond.github.io/Spatial/chp13_0.html#monte-carlo-approach-to-estimating-significance"
class="uri">https://mgimond.github.io/Spatial/chp13_0.html#monte-carlo-approach-to-estimating-significance</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
